### ISSUE TITLE
External changes to trigger release

### ISSUE THREAD

**Issue by yyynnn** [qiwi/multi-semantic-release#15]
Hi there!
Great library/fork!)

Is there a way to collect a list of extrnal deps to trigger release/bump versions of all or some packages via config?

For example:
edits in global babel config -> new build artifacts -> minor version bump for all packages

**Comment by antongolub** [comment]
Hey, @yyynnn,

We have nothing like that out of box.  ¯\\\_(ツ)\_/¯ 
But you may try to create a tech/infra package and put the babel config in it, and then refer through
```json
{
    "extends": "./packages/infra/.babelrc"
}
```
Other @scope/packages should have @scope/infra-package as dev/optional dep, for example.  So `perf(infra): tune up babel config` commit that changes files in `./packages/infra` will also trigger release of the all chained packages.
