### ISSUE TITLE
Regular tags in repo

### ISSUE THREAD

**Issue by yyynnn** [qiwi/multi-semantic-release#18]
Hi guys!
I try to manage a monorepo with multi-semantic-release inside a monolith repo. Transitional stages.
So there are regular tags already present (1.0.0).

Will there be any trouble with regular, non-scoped tags (@ui/eslint-config@1.0.0)?
like this
```
error: cannot lock ref 'refs/tags/1.2.2': Unable to create '/builds/ui/.git/refs/tags/1.2.2.lock': File exists.
```

Should I delete regular tags or maybe scope them too?

**Comment by oljekechoro** [comment]
Hi! We have never tried doing this, so we can't  answer to your question exactly. But multi-semantic-release is just a wrapper for semantic-release, so you can try to do it, but of course with making a backup beforehand.

**Comment by yyynnn** [comment]
well
no troubles with regular tags
closing)
