### ISSUE TITLE
Control dependency update on npm stage

### ISSUE THREAD

**Issue by yyynnn** [qiwi/multi-semantic-release#19]
Hi!

Is there a way to control the dependency version bump in package.json? Right now "version" and deps are updated
via npm plugin. But I didn't found any code specific in that repo
https://github.com/semantic-release/npm/blob/master/lib/prepare.js

```
{
    "name": "@scope/test-package",
    "version": "1.0.0", <- bump
...............
    "dependencies": {
        "@scope/test-package_beta": "1.0.0" <- bump (optional, via some key in cli)
    }
}
```

**Comment by antongolub** [comment]
Hey, @yyynnn,

I'm afraid this behaviour is just hardcoded and could not be configured at this time. 
Similar issue: https://github.com/dhoulb/multi-semantic-release/issues/37

**Comment by yyynnn** [comment]
@antongolub Could you point to a specific lines then?
So I could fork

**Comment by antongolub** [comment]
Sure. 

Changes detection: https://github.com/qiwi/multi-semantic-release/blob/master/lib/hasChangedDeep.js
Release type resolver: https://github.com/qiwi/multi-semantic-release/blob/master/lib/createInlinePluginCreator.js#L144

**Comment by yyynnn** [comment]
@antongolub coll thanks!
