### ISSUE TITLE
Replace `bash-glob` with `fast-glob` / `globby`

### ISSUE THREAD

**Issue by antongolub** [qiwi/multi-semantic-release#36]
* https://www.npmtrends.com/bash-glob-vs-glob-vs-fast-glob-vs-globby
* https://github.com/micromatch/bash-glob/pull/4

**Comment by davikawasaki** [comment]
@antongolub I have replaced with [`node-glob`](https://github.com/isaacs/node-glob). Would you prefer `fast-glob` or `globby`? I'm in favor with one that accepts a **ignore** option.

**Comment by davikawasaki** [comment]
Using `globby` now after #42 was merged.

**Comment by antongolub** [comment]
Released in [v3.13.0](https://github.com/qiwi/multi-semantic-release/releases/tag/v3.13.0)
