### ISSUE TITLE
Ignore certain packages to go through the workflow

### ISSUE THREAD

**Issue by davikawasaki** [qiwi/multi-semantic-release#37]
@antongolub do we have a feature that enable the semantic release workflow to fully ignore packages we want? For instance, I have three packages:

- lib
- app
- admin

What I'd want to have is have only app and admin be bumped and released, whilst the lib to maintain in the same version. If not, can you walk me through which points in the code should we tweak to enable such functionality?

**Comment by antongolub** [comment]
@davikawasaki,

by default **msr** relies on `package.json.workspaces` value, but it's very easy override with custom glob pattern.
I suggest to introduce `workspaces` CLI flag / JS API option and handle this value in `getWorkspaces`.

```
["packages/*"] — include all
["packages/*", "!packages/app"] — exclude `app`
["packages/admin"] — include `admin` only
```
**meow** parser support "array-like" args notation, I checked: https://github.com/imagemin/imagemin-cli/pull/23/files

```js
	// Imports.
	const getWorkspacesYarn = require("../lib/getWorkspacesYarn");
	const multiSemanticRelease = require("../lib/multiSemanticRelease");
	const multisemrelPkgJson = require("../package.json");
	const semrelPkgJson = require("semantic-release/package.json");

	// Get directory.
	const cwd = process.cwd();

	// Catch errors.
	try {
		console.log(`multi-semantic-release version: ${multisemrelPkgJson.version}`);
		console.log(`semantic-release version: ${semrelPkgJson.version}`);
		console.log(`flags: ${JSON.stringify(flags, null, 2)}`);

		// Get list of package.json paths according to Yarn workspaces.
		const paths = getWorkspaces(cwd, flags.workspaces);
		console.log("yarn paths", paths);
```

**Comment by davikawasaki** [comment]
@antongolub so basically what's needed is parsing the `package.json.workspaces` value?

**Comment by antongolub** [comment]
Yep, it's needed to override this value in some way.

**Comment by davikawasaki** [comment]
Thanks, I'll have something done and send here.

**Comment by davikawasaki** [comment]
Working after #42 is merged. Closing.
